name: Mirror to GitHub

# Запуск при любом push в ветку main
on:
  push:
    branches:
      - main

# Указываем, где будет выполняться job
jobs:
  mirror:
    runs-on: default

    steps:
      # 1. Клонируем текущий репозиторий из GitVerse
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Забираем всю историю

      # 2. Настраиваем Git
      - name: Configure Git
        run: |
          git config user.name "GitVerse Bot"
          git config user.email "bot@gitverse.ru"

      # 3. Добавляем удалённый репозиторий на GitHub и пушим
      - name: Push to GitHub
        run: |
          git remote add github https://x-access-token:${{ secrets.REFERENT2 }}@github.com/fedorkrs33-web/referent2.git
          git push github main --force

